# Generated by Django 3.2.6 on 2021-12-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0004_alter_amazon_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazon',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ebay',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
