# Generated by Django 3.2.6 on 2021-12-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0005_auto_20211208_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
