# Generated by Django 3.2.6 on 2021-12-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0007_auto_20211208_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importexcels',
            name='title',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
