# Generated by Django 3.2.6 on 2021-12-09 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0008_alter_importexcels_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazon',
            name='product_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amazons', to='parsing.importexcels'),
        ),
        migrations.AddField(
            model_name='ebay',
            name='product_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ebays', to='parsing.importexcels'),
        ),
        migrations.AddField(
            model_name='importexcels',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='walmart',
            name='product_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='walmarts', to='parsing.importexcels'),
        ),
    ]
