# Generated by Django 3.2.6 on 2021-12-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0010_auto_20211209_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='importexcels',
            name='url',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
