# Generated by Django 3.2.6 on 2021-12-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0011_importexcels_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='importexcels',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
