# Generated by Django 3.2.6 on 2021-12-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0012_importexcels_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importexcels',
            name='title',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
