# Generated by Django 3.2.6 on 2021-12-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0013_alter_importexcels_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importexcels',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
