# Generated by Django 3.2.6 on 2021-12-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0017_auto_20211214_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebay',
            name='url',
            field=models.URLField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='importexcels',
            name='url',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
