# Generated by Django 3.2.6 on 2021-12-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0019_auto_20211214_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ebay',
            options={'ordering': ('-quantity',)},
        ),
        migrations.AlterField(
            model_name='importexcels',
            name='status',
            field=models.CharField(choices=[('1', 'imported'), ('2', 'edited'), ('3', 'parsing'), ('4', 'parsed')], default='1', max_length=25),
        ),
    ]
