# Generated by Django 3.2.6 on 2021-12-14 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0020_auto_20211214_1823'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Walmart',
        ),
    ]
