# Generated by Django 3.2.6 on 2021-12-18 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0021_delete_walmart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazon',
            name='product_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amazons', to='parsing.importexcels'),
        ),
        migrations.AlterField(
            model_name='ebay',
            name='product_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ebays', to='parsing.importexcels'),
        ),
    ]
