# Generated by Django 3.2.6 on 2021-12-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0023_remove_importexcels_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='importexcels',
            name='color',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='importexcels',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название компании'),
        ),
        migrations.AddField(
            model_name='importexcels',
            name='item_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название продукта'),
        ),
        migrations.AddField(
            model_name='importexcels',
            name='volume',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Объем'),
        ),
    ]
