# Generated by Django 3.2.6 on 2021-12-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0024_auto_20211218_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importexcels',
            name='color',
        ),
        migrations.AddField(
            model_name='importexcels',
            name='unique_value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='amazon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ebay',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='importexcels',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='importexcels',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
