# Generated by Django 3.2.6 on 2021-12-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0025_auto_20211220_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importexcels',
            name='status',
            field=models.CharField(choices=[('1', 'imported'), ('2', 'parsing'), ('3', 'parsed')], default='1', max_length=25),
        ),
    ]
