# Generated by Django 3.2.6 on 2021-12-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0026_alter_importexcels_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importexcels',
            name='company',
        ),
        migrations.RemoveField(
            model_name='importexcels',
            name='item_title',
        ),
        migrations.RemoveField(
            model_name='importexcels',
            name='unique_value',
        ),
        migrations.RemoveField(
            model_name='importexcels',
            name='volume',
        ),
        migrations.AddField(
            model_name='importexcels',
            name='annotations',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
