# Generated by Django 3.2.6 on 2022-01-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0027_auto_20211227_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebay',
            name='similarity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
