# Generated by Django 3.2.6 on 2022-01-17 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0028_ebay_similarity'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbayAll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True, verbose_name='Название')),
                ('url', models.URLField(blank=True, max_length=5000, null=True)),
                ('star', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('percent', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('similarity', models.IntegerField(blank=True, null=True)),
                ('product_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ebaysall', to='parsing.importexcels')),
            ],
            options={
                'ordering': ('-quantity',),
            },
        ),
    ]
