# Generated by Django 3.2.6 on 2022-01-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0029_ebayall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebay',
            name='similarity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сходство'),
        ),
        migrations.AlterField(
            model_name='ebayall',
            name='similarity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сходство'),
        ),
    ]
