# Generated by Django 3.2.6 on 2022-01-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0030_auto_20220117_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazon',
            name='similarity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сходство'),
        ),
    ]
