# Generated by Django 3.2.6 on 2022-02-01 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0033_proxies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazon',
            name='product_title',
        ),
        migrations.RemoveField(
            model_name='amazonall',
            name='product_title',
        ),
        migrations.DeleteModel(
            name='Proxies',
        ),
        migrations.DeleteModel(
            name='Amazon',
        ),
        migrations.DeleteModel(
            name='AmazonAll',
        ),
    ]
